name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Checkout repo
      # Dispatch web
      # https://vitejs.dev/guide/static-deploy.html#github-pages